# Site settings
title: 实验测试
description: 静态界面
keywords: Modern, Blogging, Fun
author: Bob 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "diantongqingjie.github.io" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
