# Site settings
title: Modern Blog V2
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Nadun
baseurl: "" # the subpath of your site, e.g. /blog/
url: "diantongqingjie.github.io" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
